P_CC = ./tools/owcc.pl
P_RC = true
P_CFLAGS = -b win32 -I$(WATCOM)/h/nt -std=c99
P_LDFLAGS = -b win32
AFTERCMD = wrc -q -i=include -i=$(WATCOM)/h/nt -bt=nt src/indigo.rc indigo.exe

include Makefile.windows
